# Generated by Django 5.2.7 on 2025-10-19 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='is_verified',
            field=models.BooleanField(default=False, help_text='Indicates if the store is verified by admin'),
        ),
    ]
