# Generated by Django 5.2.7 on 2025-10-18 01:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0004_simplify_claims'),
    ]

    operations = [
        # Drop ClaimTimeline table
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS claims_claimtimeline CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
