# Generated by Django 5.2.7 on 2025-10-18 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_add_claim_attachment'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ClaimTimeline',
        ),
    ]
