# Generated by Django 5.2.7 on 2025-10-18 08:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('claims', '0006_add_claim_attachment'),
    ]

    operations = [
        # Use RunSQL with IF EXISTS to handle cases where table was already dropped
        migrations.RunSQL(
            sql='DROP TABLE IF EXISTS claims_claimtimeline CASCADE;',
            reverse_sql=migrations.RunSQL.noop
        ),
    ]
