# Generated by Django 5.2.7 on 2025-10-17 10:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items', models.TextField(help_text='Product names or description')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('Sent', 'Sent'), ('Pending', 'Pending')], max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_receipts', to=settings.AUTH_USER_MODEL)),
                ('retailer', models.ForeignKey(limit_choices_to={'role': 'retailer'}, on_delete=django.db.models.deletion.CASCADE, related_name='retailer_receipts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
