# Generated by Django 5.2.7 on 2025-10-18 03:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_add_product_specs_to_item'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='receipt',
            options={'ordering': ['-created_at']},
        ),
    ]
