# Generated by Django 5.2.7 on 2025-10-18 03:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0007_alter_receipt_options'),
        ('warranties', '0005_remove_status_field'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warranty',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Warranties'},
        ),
        migrations.AlterField(
            model_name='warranty',
            name='receipt_item',
            field=models.OneToOneField(help_text='Each receipt item can only have one warranty', on_delete=django.db.models.deletion.CASCADE, related_name='warranty', to='receipts.receiptitem'),
        ),
    ]
