# Generated by Django 5.2.7 on 2025-10-18 09:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warranties', '0006_alter_warranty_options_alter_warranty_receipt_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerWarranty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(help_text='Product name', max_length=255)),
                ('expiry_date', models.DateField(help_text='Warranty expiry date')),
                ('warranty_image', models.ImageField(help_text='Photo or scan of warranty document', upload_to='customer_warranties/%Y/%m/')),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this warranty')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(limit_choices_to={'role': 'customer'}, on_delete=django.db.models.deletion.CASCADE, related_name='customer_warranties', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Customer Warranty',
                'verbose_name_plural': 'Customer Warranties',
                'ordering': ['-created_at'],
            },
        ),
    ]
