# Generated by Django 5.2.7 on 2025-10-18 03:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('NEW_RECEIPT', 'New Receipt'), ('NEW_CLAIM', 'New Claim'), ('CLAIM_STATUS_UPDATE', 'Claim Status Updated'), ('CLAIM_NOTE_ADDED', 'Claim Note Added'), ('CLAIM_ATTACHMENT_ADDED', 'Claim Attachment Added'), ('WARRANTY_EXPIRING', 'Warranty Expiring Soon'), ('WARRANTY_EXPIRED', 'Warranty Expired')], max_length=50)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_object_type', models.CharField(blank=True, choices=[('Receipt', 'Receipt'), ('Claim', 'Claim'), ('Warranty', 'Warranty'), ('ReceiptItem', 'Receipt Item')], max_length=50, null=True)),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actions', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'is_read'], name='notificatio_user_id_427e4b_idx'), models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx')],
            },
        ),
    ]
