# Generated by Django 5.2.7 on 2025-10-18 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('WELCOME', 'Welcome Message'), ('NEW_RECEIPT', 'New Receipt'), ('NEW_CLAIM', 'New Claim'), ('CLAIM_STATUS_UPDATE', 'Claim Status Updated'), ('CLAIM_NOTE_ADDED', 'Claim Note Added'), ('CLAIM_ATTACHMENT_ADDED', 'Claim Attachment Added'), ('WARRANTY_EXPIRING', 'Warranty Expiring Soon'), ('WARRANTY_EXPIRED', 'Warranty Expired')], max_length=50),
        ),
    ]
